### ISSUE TITLE
Logging method 

### ISSUE THREAD

**Issue by guysoft** [Tikkun-olam/angelzzz#1]
Hey,
So currently we have a script that outputs to a file a gzipped csv with the data.
I want to create a  service that sits, makes the sure the beddit is connected and monitors.

So the depressions we need are :
1. Are we going to use something like an sqlite database, and then we can pull queries from that?
2. are we going to have rotating logs?
   cc @matanninio ( @arnonzamir if you have any input)

**Comment by arnonzamir** [comment]
Is Stacy using the device? Are we working with real and new data?
Arnon Zamir
TOM: Founding Director
+972-52-8836099 |arnon@tomglobal.org

TEDx|linkedin |TOM in action
mail too short?here's why.

On Thu, Oct 20, 2016 5:11 PM, Guy Sheffer notifications@github.com
wrote:
Hey,
So currently we have a script that outputs to a file a gzipped csv with the
data.
I want to create a service that sits, makes the sure the beddit is connected and
monitors.

So the depressions we need are :
1. Are we going to use something like an sqlite database, and then we can pull
   queries from that?
2. are we going to have rotating logs?
   cc @matanninio  ( @arnonzamir  if you have any input)

**Comment by guysoft** [comment]
@arnonzamir She has been using the app on the phone for the moment. I want to get the bluetooth stack communication stable before I instruct her how to set it up, see the [auto connect branch](https://github.com/Tikkun-olam/angelzzz/commits/auto_connect) I am working on. Its getting there, but there is a bit more exception handling required.
This is off-topic so I am opening a new issue

**Comment by guysoft** [comment]
Using sqlite for now
